springs:
- joint_name: joint0
  K: 4700
  D: 1000
  upper_limit: 1.0
  lower_limit: -1.0
  velocity_limit: 20.0
- joint_name: joint1
  K: 4700
  D: 1000
  upper_limit: 1.0
  lower_limit: -1.0
  velocity_limit: 20.0
- joint_name: joint2
  K: 4700
  D: 1000
  upper_limit: 1.0
  lower_limit: -1.0
  velocity_limit: 20.0
- joint_name: joint3
  K: 4700
  D: 1000
  upper_limit: 1.0
  lower_limit: -1.0
  velocity_limit: 20.0
- joint_name: joint4
  K: 4700
  D: 1000
  upper_limit: 1.0
  lower_limit: -1.0
  velocity_limit: 20.0
