// Generated by gencpp from file baseline_footstep_planner/FootstepSequence2DStamped.msg
// DO NOT EDIT!


#ifndef BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2DSTAMPED_H
#define BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2DSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <baseline_footstep_planner/FootstepSequence2D.h>

namespace baseline_footstep_planner
{
template <class ContainerAllocator>
struct FootstepSequence2DStamped_
{
  typedef FootstepSequence2DStamped_<ContainerAllocator> Type;

  FootstepSequence2DStamped_()
    : header()
    , sequence()  {
    }
  FootstepSequence2DStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sequence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator>  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> const> ConstPtr;

}; // struct FootstepSequence2DStamped_

typedef ::baseline_footstep_planner::FootstepSequence2DStamped_<std::allocator<void> > FootstepSequence2DStamped;

typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2DStamped > FootstepSequence2DStampedPtr;
typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2DStamped const> FootstepSequence2DStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baseline_footstep_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18521c3629e10bc5eb159b2a2ca397ab";
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18521c3629e10bc5ULL;
  static const uint64_t static_value2 = 0xeb159b2a2ca397abULL;
};

template<class ContainerAllocator>
struct DataType< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baseline_footstep_planner/FootstepSequence2DStamped";
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"FootstepSequence2D sequence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: baseline_footstep_planner/FootstepSequence2D\n"
"Footstep2D[] footsteps\n"
"\n"
"================================================================================\n"
"MSG: baseline_footstep_planner/Footstep2D\n"
"int8 LEFT=0\n"
"int8 RIGHT=1\n"
"\n"
"int8 foot_lr\n"
"geometry_msgs/Pose2D foot_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FootstepSequence2DStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baseline_footstep_planner::FootstepSequence2DStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sequence: ";
    s << std::endl;
    Printer< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >::stream(s, indent + "  ", v.sequence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2DSTAMPED_H
