// Generated by gencpp from file baseline_footstep_planner/FootstepSequence2D.msg
// DO NOT EDIT!


#ifndef BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2D_H
#define BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <baseline_footstep_planner/Footstep2D.h>

namespace baseline_footstep_planner
{
template <class ContainerAllocator>
struct FootstepSequence2D_
{
  typedef FootstepSequence2D_<ContainerAllocator> Type;

  FootstepSequence2D_()
    : footsteps()  {
    }
  FootstepSequence2D_(const ContainerAllocator& _alloc)
    : footsteps(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >> _footsteps_type;
  _footsteps_type footsteps;





  typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> const> ConstPtr;

}; // struct FootstepSequence2D_

typedef ::baseline_footstep_planner::FootstepSequence2D_<std::allocator<void> > FootstepSequence2D;

typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2D > FootstepSequence2DPtr;
typedef boost::shared_ptr< ::baseline_footstep_planner::FootstepSequence2D const> FootstepSequence2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator2> & rhs)
{
  return lhs.footsteps == rhs.footsteps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baseline_footstep_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d7253025f3e5ddf09047640b33d4044";
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d7253025f3e5ddfULL;
  static const uint64_t static_value2 = 0x09047640b33d4044ULL;
};

template<class ContainerAllocator>
struct DataType< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baseline_footstep_planner/FootstepSequence2D";
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Footstep2D[] footsteps\n"
"\n"
"================================================================================\n"
"MSG: baseline_footstep_planner/Footstep2D\n"
"int8 LEFT=0\n"
"int8 RIGHT=1\n"
"\n"
"int8 foot_lr\n"
"geometry_msgs/Pose2D foot_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.footsteps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FootstepSequence2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baseline_footstep_planner::FootstepSequence2D_<ContainerAllocator>& v)
  {
    s << indent << "footsteps[]" << std::endl;
    for (size_t i = 0; i < v.footsteps.size(); ++i)
    {
      s << indent << "  footsteps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >::stream(s, indent + "    ", v.footsteps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEPSEQUENCE2D_H
