// Generated by gencpp from file baseline_footstep_planner/Footstep2D.msg
// DO NOT EDIT!


#ifndef BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEP2D_H
#define BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEP2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace baseline_footstep_planner
{
template <class ContainerAllocator>
struct Footstep2D_
{
  typedef Footstep2D_<ContainerAllocator> Type;

  Footstep2D_()
    : foot_lr(0)
    , foot_pose()  {
    }
  Footstep2D_(const ContainerAllocator& _alloc)
    : foot_lr(0)
    , foot_pose(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _foot_lr_type;
  _foot_lr_type foot_lr;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _foot_pose_type;
  _foot_pose_type foot_pose;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LEFT)
  #undef LEFT
#endif
#if defined(_WIN32) && defined(RIGHT)
  #undef RIGHT
#endif

  enum {
    LEFT = 0,
    RIGHT = 1,
  };


  typedef boost::shared_ptr< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> const> ConstPtr;

}; // struct Footstep2D_

typedef ::baseline_footstep_planner::Footstep2D_<std::allocator<void> > Footstep2D;

typedef boost::shared_ptr< ::baseline_footstep_planner::Footstep2D > Footstep2DPtr;
typedef boost::shared_ptr< ::baseline_footstep_planner::Footstep2D const> Footstep2DConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator2> & rhs)
{
  return lhs.foot_lr == rhs.foot_lr &&
    lhs.foot_pose == rhs.foot_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator1> & lhs, const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baseline_footstep_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9b527870d832ddd9af7e14a6b253360";
  }

  static const char* value(const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9b527870d832dddULL;
  static const uint64_t static_value2 = 0x9af7e14a6b253360ULL;
};

template<class ContainerAllocator>
struct DataType< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baseline_footstep_planner/Footstep2D";
  }

  static const char* value(const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 LEFT=0\n"
"int8 RIGHT=1\n"
"\n"
"int8 foot_lr\n"
"geometry_msgs/Pose2D foot_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.foot_lr);
      stream.next(m.foot_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Footstep2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baseline_footstep_planner::Footstep2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baseline_footstep_planner::Footstep2D_<ContainerAllocator>& v)
  {
    s << indent << "foot_lr: ";
    Printer<int8_t>::stream(s, indent + "  ", v.foot_lr);
    s << indent << "foot_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASELINE_FOOTSTEP_PLANNER_MESSAGE_FOOTSTEP2D_H
