FootManager:
  footstepDuration: 1.2 # [sec]
  doubleSupportRatio: 0.2 # []

CentroidalManager:
  refComZ: 0.81 # [m]

transitions:
  - [BWC::Initial_, OK, BWC::ConfigWalk_, Auto]

states:
  BWC::Initial_:
    base: BWC::Initial
    configs:
      autoStartTime: 2.0

  BWC::ConfigWalk_:
    base: BWC::ConfigWalk
    configs:
      footstepList:
        # 1歩目: 左足を前に出す（歩幅を0.4メートルに設定）
        - foot: Left
          footMidpose:
            translation: [0.4, 0.0, 0.0] # x軸方向に0.4メートル
          startTime: 2.0
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.05]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.05]

        # 2歩目: 右足を前に出す（同じく0.4メートル）
        - footMidpose:
            translation: [0.4, 0.0, 0.0] # 同じくx軸方向に0.4メートル
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.05]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.05]

        # 3歩目: 左足で段差を上る（x軸方向にさらに前進し、z軸方向の高さを下げる）
        - footMidpose:
            translation: [0.85, 0.0, 0.1] # x軸方向に0.85メートル進み、z軸方向に0.1メートル
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.08]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.08]

        # 4歩目: 右足を段差に揃える
        - footMidpose:
            translation: [0.85, 0.0, 0.095] # 右足も同じく段差に揃える
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.15]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.15]

        # 5歩目: 左足でさらに段差を上る
        - footMidpose:
            translation: [1.30, 0.0, 0.1] # x軸方向に1.30メートル進み、z軸方向に0.1メートル
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.08]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.08]

        # 6歩目: 右足を段差に揃える
        - footMidpose:
            translation: [1.30, 0.0, 0.095] # 右足も同じく段差に揃える
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.15]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.15]

        # 7歩目: 左足でさらに段差を上る
        - footMidpose:
            translation: [1.75, 0.0, 0.1] # 左足をさらに段差を上る (x軸方向に1.75メートル、z軸は0.1メートル)
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.08] # 左足も高めに持ち上げる
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.08]

        # 8歩目: 右足を段差に揃える
        - footMidpose:
            translation: [1.75, 0.0, 0.095] # 右足も同じく段差に揃える
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.15] # 右足も高めに持ち上げる
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.15]
