MainRobot: CHIDORI

Enabled: BaselineWalkingController
ControllerModulePaths: ["/bwc_ws/devel/.private/baseline_walking_controller/lib/mc_controller/"]

LogDirectory: /userdir/chidori_LOG/bins

Timestep: 0.002
